baseURL = "http://johnnyclee.com/"
languageCode = "en-us"
title = "Johnny Lee"
theme = "minimal"
googleAnalytics = "UA-159362155-1"
publishDir = "../public_www/"

[params]
    author = "Johnny Lee"
    description = "Personal website"
    githubUsername = "leecjohnny"
    accent = "orange"
    showBorder = true
    backgroundColor = "white"
    font = "Roboto" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "python", "r", "sql"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/projects/"
    name = "Projects"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:me@johnnyclee.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/leecjohnny/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://linkedin.com/in/johnny-c-lee/"
    name = "linkedin"
    weight = 3
